version: "3.3"
services:
    ffbo.processor:
        container_name: ffbo.processor
        image: fruitflybrain/ffbo.processor:hemibrain
        ports:
            - target: 8081
              published: 8081
              protocol: tcp
              mode: host
            - target: 8082
              published: 8082
              protocol: tcp
              mode: host
        tty: true
        volumes:
            - type: bind
              source: .
              target: /config
        networks:
            - ffbonet
    ffbo.nlp_component:
        container_name: ffbo.nlp_component
        image: fruitflybrain/ffbo.nlp_component:hemibrain
        tty: true
        volumes:
            - type: bind
              source: .
              target: /config
        networks:
            - ffbonet
    ffbo.neuroarch_component:
        container_name: ffbo.neuroarch_component
        image: fruitflybrain/ffbo.neuroarch_component:hemibrain
        tty: true
        volumes:
            - type: bind
              source: .
              target: /config
        networks:
            - ffbonet
    ffbo.neurokernel_component:
        container_name: ffbo.neurokernel_component
        image: fruitflybrain/ffbo.neurokernel_component
        tty: true
        volumes:
            - type: bind
              source: .
              target: /config
        networks:
            - ffbonet
networks:
    ffbonet:
        driver: bridge
